Simplex iteration

In [1]:
import numpy as np 
from fractions import Fraction
np.set_printoptions(formatter={'all':lambda x: str(Fraction(x).limit_denominator())})

In [2]:
# Ex 
# min z 
#     -6x1     +x3 -2x4 +2x5 =6
#     -3x1 +x2     +6x4 +3x5 =15
#      5x1         +3x4 -2x5 =-21

# X=np.array([[-6,0,1,-2,2,6],
#             [-3,1,0,6,3,15],
#             [5,0,0,3,-2,-21],
#             ],dtype=float)

X=np.array([[-2,0,6,2,0,-3,1,20],
            [-4,1,7,1,0,-1,0,10],
            [0,0,-5,3,1,-1,0,60],
            [0,0,13,-6,0,2,0,110]
            ],dtype=float)

In [3]:
m=np.shape(X)[0]-1
n=np.shape(X)[1]-1
nb=n+1

F=np.zeros(n) # 給 basic feasible sol空間
label=np.zeros(m) # 給 table左邊那排 label空間
tt=0 # 係數為正的數量
num=0 # 跌代次數
while tt !=n:

    tlabel=0
    tt=0 # 係數為正的數量

    # 找basic variable當label
    for j in np.arange(m):
        for i in np.arange(n):
            if X[j][i]==1 and np.sum(X[:,i])==1:
                label[j]=i+1


    mlabel=np.array([]) # 係數為負
    for t in np.arange(n):
        if X[m,t] >= 0:
            tt=tt+1
        else:
            mlabel=np.append(mlabel,t)

    if tt ==n: # 全部係數都為正 print答案
        sol=X[m,n]
        
        for f in np.arange(m):
            ff=int(label[f]-1)
            F[ff]=X[f,n]
        
        print("\n-----------------------------------\n")
        print("跌代"+str(num)+"次")
        print("basic variables (index): "+str(label))
        print("basic feasible solution: "+str(F))
        print("minimize: "+str(-sol))
        break

    # 檢查 bounded below

    # 找目標含數裡係數負的 min 得出pivoting column
    M=np.array([])
    for mm in np.arange(len(mlabel)):
        M=np.append(M,X[m,int(mlabel[mm])])

    M=np.min(M)

    for mmm in np.arange(n):
        if X[m,mmm]==M:
           ttt=mmm 
    
    tlabel=ttt # column

    # 找column上面係數為正
    Bb=np.array([])
    for k in np.arange(m):
        if X[k,tlabel]>0:
            Bb=np.append(Bb,k)

    # 找column上面係數為正 且 b/a的 min
    B=np.array([])

    for kk in np.arange(len(Bb)):
        bbb=int(Bb[kk])
        B=np.append(B,X[bbb,n]/X[bbb,tlabel])

    B=np.min(B)   
    for kkk in np.arange(m):   
        if X[kkk,n]/X[kkk,tlabel]==B:
            ll=kkk # ll是pivot row

    label[ll]=tlabel+1 # tlabel是column

    # pivot係數變1
    if X[ll,tlabel] !=1:
        X[ll,:]=X[ll,:]/X[ll,tlabel]

    # pivot其他變0
    Xtemp = X[ll,:].copy()
    for kkkk in np.arange(m+1):
        X[kkkk,:]=X[kkkk,:]-X[kkkk,tlabel]*Xtemp
    X[ll,:]=Xtemp

    print()
    print(X) # 轉換一次的form
    num=num+1


[[6 -2 -8 0 0 -1 1 0]
 [-4 1 7 1 0 -1 0 10]
 [12 -3 -26 0 1 2 0 30]
 [-24 6 55 0 0 -4 0 170]]

[[1 -1/3 -4/3 0 0 -1/6 1/6 0]
 [0 -1/3 5/3 1 0 -5/3 2/3 10]
 [0 1 -10 0 1 4 -2 30]
 [0 -2 23 0 0 -8 4 170]]

[[1 -7/24 -7/4 0 1/24 0 1/12 5/4]
 [0 1/12 -5/2 1 5/12 0 -1/6 45/2]
 [0 1/4 -5/2 0 1/4 1 -1/2 15/2]
 [0 0 3 0 2 0 0 230]]

-----------------------------------

跌代3次
basic variables (index): [1 4 6]
basic feasible solution: [5/4 0 0 45/2 0 15/2 0]
minimize: -230.0
