In [1]:
import numpy as np
from fractions import Fraction
np.set_printoptions(formatter={'all':lambda x: str(Fraction(x).limit_denominator())})

3.(a) Gram-Schmidt:

$$
v_k=w_k-\sum_{i=1}^{k-1}\frac{\lang w_k,v_i\rang}{\|v_i\|^2}v_i\tag{Thm 6.4}
$$

*see code below*

to get the orthonormal basis, we normalize $v_1$ and $v_2$:

$$
e_1=\frac{v_1}{\|v_1\|}=\begin{pmatrix}\frac{\sqrt{6}}{6}\\\frac{\sqrt{6}}{3}\\\frac{\sqrt{6}}{6}\\0\end{pmatrix},\ \ \ \ \
e_2=\frac{v_2}{\|v_2\|}=\begin{pmatrix}-\frac{\sqrt{30}}{15}\\-\frac{\sqrt{30}}{30}\\\frac{2\sqrt{30}}{15}\\\frac{\sqrt{30}}{10}\end{pmatrix}
$$


In [2]:
def GramSchmidt(w_vector, v_set:list):
    for v_i in v_set:
        print(np.dot(w_vector, v_i) / np.dot(v_i, v_i))
        w_vector -= (np.dot(w_vector, v_i) / np.dot(v_i, v_i))*v_i
    return w_vector

w1 = np.array([1, 2, 1, 0], dtype=float)
w2 = np.array([0, 1, 2, 1], dtype=float)
w3 = np.array([1, 0, -3, -2], dtype=float)

v_set = [] # make an empty list for v_set

v1 = w1 # let v1 = w1
print("v1:", v1)
v_set.append(v1) # add v1 into v_set

v2 = GramSchmidt(w2, v_set)
print("v2:", v2)
v_set.append(v2) # add v2 into v_set

v3 = GramSchmidt(w3, v_set)
print("v3:", v3)

v1: [1 2 1 0]
0.6666666666666666
v2: [-2/3 -1/3 4/3 1]
-0.3333333333333333
-2.0
v3: [0 0 0 0]


3.(c) check $A=QR$

In [3]:
Q = np.array([[np.sqrt(6)/6, -np.sqrt(30)/15, 1/2],
              [np.sqrt(6)/3, -np.sqrt(30)/30, -1/2],
              [np.sqrt(6)/6, 2*np.sqrt(30)/15, 1/2],
              [0, np.sqrt(30)/10, -1/2]])
R = np.array([[np.sqrt(6), 2*np.sqrt(6)/3, -np.sqrt(6)/3],
              [0, np.sqrt(30)/3, -2*np.sqrt(30)/3],
              [0, 0, 0]])
print(np.dot(Q, R))

[[1 0 1]
 [2 1 0]
 [1 2 -3]
 [0 1 -2]]


5.(a) check $Ax=RQx=b$

In [4]:
Q = np.array([[1/2, 1/np.sqrt(2), 0],
              [1/2, 0, -1/np.sqrt(2)],
              [1/2, -1/np.sqrt(2), 0], 
              [1/2, 0, 1/np.sqrt(2)]])

R = np.array([[2*np.sqrt(2), 2*np.sqrt(2), 4*np.sqrt(2)],
              [0, 2*np.sqrt(2), -np.sqrt(2)],
              [0, 0, np.sqrt(2)]])

A = np.dot(Q, R)
x = np.array([(7/2)*np.sqrt(2)-3, -1, 2])

print(np.dot(A, x))

[3 5 11 9]


5.(b) compute $P=A(A^TA)^{-1}A^T=QQ^T$

In [5]:
print(Q@Q.T)

[[3/4 1/4 -1/4 1/4]
 [1/4 3/4 1/4 -1/4]
 [-1/4 1/4 3/4 1/4]
 [1/4 -1/4 1/4 3/4]]
